# Generated by Django 4.1.4 on 2022-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_ip', models.CharField(max_length=100)),
                ('ledState', models.BooleanField(default=False)),
                ('doorState', models.BooleanField(default=False)),
                ('alarmState', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('bodySensor', models.BooleanField(default=False)),
            ],
        ),
    ]
